Rentalgo/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('signup/', views.signup.as_view(), name='signup'),
    path('login/', views.user_login ,name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/',views.user_profile, name='profile'),
    path('getKyc/',views.getKyc, name='getKyc'),
    path('delete/<int:product_id>/', views.delete_product, name='delete'),
    path('orders/',views.orders, name='orders'),
]

Rentalgo/products/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:product_id>', views.detail, name='detail'),
    path('order/<int:product_id>', views.new_order, name='new_order'),
    path('payment_status/', views.verify_payment, name='status'),
    path('buy_payment_status/', views.buy_payment, name='buy_status'),
    path('buyorder/<int:product_id>', views.buy_order, name='buy_order'),

]

Rentalgo/rentalgo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path("about/", views.about, name="AboutUs"),
path("contact/", views.contact,name="Contactus",),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rentalgo/products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Product(models.Model):
    prod_name = models.CharField(max_length=128, blank=False)
    description = models.TextField(blank=False)
    quantity = models.PositiveIntegerField(default=1, blank=False)
    dprice = models.PositiveIntegerField()
    wprice = models.PositiveIntegerField()
    mprice = models.PositiveIntegerField()
    img1 = models.ImageField(upload_to='images/',null=True)
    img2 = models.ImageField(upload_to='images/',null=True)
    owner = models.ForeignKey(User,null=True, on_delete=models.CASCADE, related_name='products')
    selling_choice = [
        ('y','YES'),
        ('n','NO'),
    ]
    available_for_selling = models.CharField(max_length=1, choices=selling_choice, default='n')
    sprice = models.PositiveIntegerField(default=0)
    cities = [
        ('Mumbai','Mumbai'),
        ('Delhi','Delhi'),
        ('Jabalpur','Jabalpur'),
        ('Goa','Goa'),
        ('Bangalore','Bangalore'),
        ('Hyderabad','Hyderabad'),
        ('Lucknow','Lucknow'),
        ('Kanpur','Kanpur'),
        ('Gwalior','Gwalior'),
        ('Gurgaon','Gurgaon'),
    ]
    city_choice = models.CharField(max_length=15, choices=cities, default='Jabalpur')

    def __str__(self):
        return self.prod_name

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='iorder')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='myorder')
    address = models.CharField(max_length=512, blank=False)
    # city = models.CharField(max_length=64, blank=False)
    zip_code = models.PositiveIntegerField()
    contact = models.CharField(max_length=10, blank=False)
    order_date = models.DateField()
    date_range = models.CharField(max_length=128,blank=False)
    cost = models.PositiveIntegerField(null=True)
    choice = [
        ('p','PAID'),
        ('u','NOT PAID'),
    ]
    payment_status = models.CharField(max_length=1, choices=choice, default='u')
    cities = [
        ('Mumbai','Mumbai'),
        ('Delhi','Delhi'),
        ('Jabalpur','Jabalpur'),
        ('Goa','Goa'),
        ('Bangalore','Bangalore'),
        ('Hyderabad','Hyderabad'),
        ('Lucknow','Lucknow'),
        ('Kanpur','Kanpur'),
        ('Gwalior','Gwalior'),
        ('Gurgaon','Gurgaon'),
    ]
    city_choice = models.CharField(max_length=15, choices=cities, default='Jabalpur')

class BuyOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='buyorder')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buyiorder')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buymyorder')
    address = models.CharField(max_length=512, blank=False)
    # city = models.CharField(max_length=64, blank=False)
    zip_code = models.PositiveIntegerField()
    contact = models.CharField(max_length=10, blank=False)
    order_date = models.DateField()
    cost = models.PositiveIntegerField(null=True)
    choice = [
        ('p','PAID'),
        ('u','NOT PAID'),
    ]
    payment_status = models.CharField(max_length=1, choices=choice, default='u')
    cities = [
        ('Mumbai','Mumbai'),
        ('Delhi','Delhi'),
        ('Jabalpur','Jabalpur'),
        ('Goa','Goa'),
        ('Bangalore','Bangalore'),
        ('Hyderabad','Hyderabad'),
        ('Lucknow','Lucknow'),
        ('Kanpur','Kanpur'),
        ('Gwalior','Gwalior'),
        ('Gurgaon','Gurgaon'),
    ]
    city_choice = models.CharField(max_length=15, choices=cities, default='Jabalpur')

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=10, default="")
    desc = models.CharField(max_length=500, default="")


    def __str__(self):
        return self.name

Rentalgo/products/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, Order, BuyOrder

class ProdForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('prod_name','description','img1','img2','quantity','dprice','wprice','mprice','available_for_selling','sprice','city_choice')
        labels = {
                    'prod_name': 'Product Name',
                    'description': 'Description',
                    'quantity': 'Quantity',
                    'img1': 'Image 1',
                    'img2': 'Image 2',
                    'dprice': 'Rent per Day',
                    'wprice': 'Rent per Week',
                    'mprice': 'Rent per Month',
                    'sprice': 'Selling Price(Fill if available for sale)',
                    'city_choice': 'This Product is available in',
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('address','zip_code','contact','date_range',)
        labels = {
                    'date_range': 'Date Range',
                    'address': 'Address',
                    # 'city': 'City',
                    'zip_code': 'Zip Code',
                    'contact': 'Mobile Number',
        }

class BuyForm(forms.ModelForm):
    class Meta:
        model = BuyOrder
        fields = ('address','zip_code','contact',)
        labels = {
                    'address': 'Address',
                    # 'city': 'City',
                    'zip_code': 'Zip Code',
                    'contact': 'Mobile Number',
        }

Rentalgo/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import forms
from .forms import ProdForm, OrderForm, BuyForm
from .models import Product, Order, BuyOrder, Contact
import datetime
from django.views.decorators.csrf import csrf_exempt
from . import Checksum


# Create your views here.
MERCHANT_KEY = 'kbzk1DSbJiV_O3p5'

def home(request):
    products = Product.objects
    return render(request, 'products/home.html', {'products':products})

@login_required
def create(request):
    if request.method == 'POST':
        prod_form = ProdForm(request.POST,request.FILES)
        if prod_form.is_valid():
            product = prod_form.save(commit=False)
            product.owner = request.user
            product.save()
            return redirect('/products/'+str(product.id))
        else:
            return render(request, 'products/create.html', {'prod_form':ProdForm})

    else:
        if request.user.profile.kyc_verified == "n":
            products = Product.objects
            return render(request, 'products/home.html', {'products':products, 'error':'Verify your kyc before posting an AD!'})

        else:
            prod_form = ProdForm
            return render(request, 'products/create.html', {'prod_form':prod_form})

def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/detail.html', {'product':product})

@login_required
def new_order(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        # Take user to payment page
        if product.quantity == 0:
            return render(request, 'products/detail.html', {'product':product})
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.product = product
            order.receiver = request.user
            order.sender = product.owner
            order.order_date = datetime.date.today()
            range = order.date_range.split(' - ')
            start = range[0].split('/')
            end = range[1].split('/')
            d1 = datetime.date( int(start[2]), int(start[1]), int(start[0]))
            d2 = datetime.date( int(end[2]), int(end[1]), int(end[0]))
            diff = d2-d1
            order.cost = (diff.days//30)*product.mprice + ((diff.days%30)//7)*product.wprice + (diff.days%7)*product.dprice
            if order.cost == 0:
                order_form = OrderForm
                return render(request, 'products/order.html', {'order_form':order_form, 'product':product, 'error':'Select two different dates'})
            order.city_choice = product.city_choice
            order.save()
            # product.quantity = product.quantity - 1
            # product.save()
            param_dict = {
                'MID': 'WorldP64425807474247',
                'ORDER_ID': str(100000000000000002837891-order.id),
                'TXN_AMOUNT': str(order.cost),
                'CUST_ID': request.user.email,
                'INDUSTRY_TYPE_ID': 'Retail',
                'WEBSITE': 'WEBSTAGING',
                'CHANNEL_ID': 'WEB',
                'CALLBACK_URL':'http://127.0.0.1:8000/products/payment_status/',
            }
            param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(param_dict, MERCHANT_KEY)
            return render(request, 'products/paytm.html', {'param_dict': param_dict})
    else:
        if request.user.profile.kyc_verified == "n":
            product=Product.objects
            return render(request, 'products/home.html',  {'product':product, 'error':'Select two different dates'})
        else:
            order_form = OrderForm
            return render(request, 'products/order.html', {'order_form':order_form, 'product':product})

@csrf_exempt
def verify_payment(request):
    form = request.POST
    response_dict = {}
    for i in form.keys():
        response_dict[i] = form[i]
        if i == 'CHECKSUMHASH':
            checksum = form[i]

    verify = Checksum.verify_checksum(response_dict, MERCHANT_KEY, checksum)
    if verify:
        if response_dict['RESPCODE'] == '01':
            order = get_object_or_404(Order, pk=100000000000000002837891-int(response_dict['ORDERID']))
            product = get_object_or_404(Product, pk=order.product.id)
            order.payment_status = 'p'
            product.quantity = product.quantity - 1
            order.save()
            product.save()
        else:
            order = get_object_or_404(Order, pk=100000000000000002837891-int(response_dict['ORDERID']))
            # product = get_object_or_404(Product, pk=order.product.id)
            # product.quantity = product.quantity + 1
            # product.save()
            order.delete()
        return render(request, 'products/paymentstatus.html', {'response': response_dict})
    else:
        redirect('home')

@login_required
def buy_order(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if product.available_for_selling == "n":
        redirect('home')
    if request.method == 'POST':
        # Take user to payment page
        if product.quantity == 0:
            return render(request, 'products/detail.html', {'product':product})
        form = BuyForm(request.POST)
        if form.is_valid():
            buyorder = form.save(commit=False)
            buyorder.product = product
            buyorder.receiver = request.user
            buyorder.sender = product.owner
            buyorder.order_date = datetime.date.today()
            buyorder.cost = product.sprice
            buyorder.city_choice = product.city_choice
            buyorder.save()
            # product.quantity = product.quantity - 1
            # product.save()
            param_dict = {
                'MID': 'WorldP64425807474247',
                'ORDER_ID': str(100000000000000382109321-buyorder.id),
                'TXN_AMOUNT': str(buyorder.cost),
                'CUST_ID': request.user.email,
                'INDUSTRY_TYPE_ID': 'Retail',
                'WEBSITE': 'WEBSTAGING',
                'CHANNEL_ID': 'WEB',
                'CALLBACK_URL':'http://127.0.0.1:8000/products/buy_payment_status/',
            }
            param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(param_dict, MERCHANT_KEY)
            return render(request, 'products/paytm.html', {'param_dict': param_dict})
    else:
        if request.user.profile.kyc_verified == "n":
            product =Product.objects
            return render(request, 'products/home.html',  {'product':product, 'error':'Select two different dates'})
        else:
            buy_form = BuyForm
            return render(request, 'products/buyorder.html', {'buy_form':buy_form, 'product':product})

@csrf_exempt
def buy_payment(request):
    form = request.POST
    response_dict = {}
    for i in form.keys():
        response_dict[i] = form[i]
        if i == 'CHECKSUMHASH':
            checksum = form[i]

    verify = Checksum.verify_checksum(response_dict, MERCHANT_KEY, checksum)
    if verify:
        if response_dict['RESPCODE'] == '01':
            buyorder = get_object_or_404(BuyOrder, pk=100000000000000382109321-int(response_dict['ORDERID']))
            product = get_object_or_404(Product, pk=buyorder.product.id)
            buyorder.payment_status = 'p'
            product.quantity = product.quantity - 1
            buyorder.save()
            product.save()
        else:
            buyorder = get_object_or_404(BuyOrder, pk=100000000000000382109321-int(response_dict['ORDERID']))
            # product = get_object_or_404(Product, pk=buyorder.product.id)
            # product.quantity = product.quantity + 1
            # product.save()
            buyorder.delete()
        return render(request, 'products/paymentstatus.html', {'response': response_dict})
    else:
        redirect('home')

def about(request):
    return render(request, 'about.html')

def contact(request):
    thank = False
    if request.method=="POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        thank = True
    return render(request, 'contactus.html', {'thank': thank})

Rentalgo/products/templates/products/buyorder.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% if error %}
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Sorry!</strong> {{ error }}
  </div>
{% endif %}
<div class="jumbotron" >
    <div class="row pb-4 pt-3">
      <div class="col-2">
        <img src="{{ product.img1.url }}" class="img-fluid">
      </div>
      <div class="col-7">
        <h4>{{ product.prod_name }}</h4>
      </div>
      <div class="col-3">
        <!-- <a href="{% url 'detail' product.id %}"><button class="btn btn-primary btn-lg btn-block" name="button">Rent</button></a>
        <br> -->
        <h5>Per Day: Rs {{ product.dprice }}</h5>
        <h5>Per Week: Rs {{ product.wprice }}</h5>
        <h5>Per Month: Rs {{ product.mprice }}</h5>
        <h5>Selling Price: Rs {{ product.sprice }}</h5>
      </div>
    </div>
    <div class="container col-4">
      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form buy_form %}
        <h5>This product is only available in: {{ product.city_choice }}</h5>
        <h5>Amount: Rs {{ product.sprice }}</h5>
        <input type="submit" class="btn btn-primary" value="Pay Now">
      </form>
    </div>
</div>

{% endblock %}

Rentalgo/products/templates/products/create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <div class="alert alert-info">
    <strong>Info!</strong> You can delete the ad later in your profile
  </div>

{% if error %}
{{ error }}
<br>
<br>
{% endif %}
<div class="container col-5">
  <div class="jumbotron" >
    <h1>Post New Ad</h1>
    <form action="{% url 'create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form prod_form %}
      <input type="submit" class="btn btn-primary" value="Create">
    </form>
  </div>
</div>

{% endblock %}

Rentalgo/products/templates/products/detail.html
{% extends 'base.html' %}

{% block content %}
{% if product.quantity == 0 %}
  <div class="alert alert-danger">
    <strong>Sorry!</strong> This item is out of stock
  </div>
{% endif %}
<div class="jumbotron">
  <div class="row">
    <div class="col-2">
      <img src="{{ product.img1.url }}" class="img-fluid" >
    </div>
    <div class="col-6">
      <h2>{{ product.prod_name }}</h2>
    </div>
    {% if product.quantity > 0 %}
      <div class="col-4">
        <a href="{% url 'new_order' product.id %}"><button class="btn btn-primary btn-lg btn-block" name="button">Rent</button></a>
      </div>
    {% endif %}

  </div>
  <br>
  <div class="row">
    <div class="col-8">
      <img src="{{ product.img2.url }}" class="img-fluid" style="height: 400px" width="400px">
    </div>
    <div class="col-4">
      <h4>Per Day: Rs {{ product.dprice }}</h4>
      <h4>Per Week: Rs {{ product.wprice }}</h4>
      <h4>Per Month: Rs {{ product.mprice }}</h4>
      <br>
      {% if product.available_for_selling == "y" %}
        {% if product.quantity > 0 %}
          <a href="{% url 'buy_order' product.id %}"><button class="btn btn-primary btn-lg btn-block" name="button">Buy</button></a>
        {% endif %}
        <h4>Selling Price: Rs {{ product.sprice }}</h4>
      {% endif %}
      <br>
      <h4>This item is only available in: {{ product.city_choice }}</h4>
    </div>

  </div>
  <br>
  <div class="row">
    <div class="col-8">
      <h5>{{ product.description }}</h5>
    </div>

  </div>
</div>

{% endblock %}

Rentalgo/products/templates/products/home.html
{% extends 'base.html' %}

{% block content %}
  {% if error %}
    <div class="alert alert-danger alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Sorry!</strong> {{ error }}
    </div>
  {% endif %}
  <div class="jumbotron">
    {% for product in products.all %}
      <div class="row pb-4 pt-3">
        <div class="col-2" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer; ;
  height: auto; " >
          <img src="{{ product.img1.url }}" class="img-fluid  "  >
        </div>
        <div class="col-7" onclick="window.location='{% url 'detail' product.id %}';"  style="cursor: pointer;">
          <h4>{{ product.prod_name }}</h4>

</div>
        <div class="col-3">
          <a href="{% url 'detail' product.id %}"><button class="btn btn-primary btn-lg btn-block" name="button">Rent or Buy</button></a>
          <br>
          <h5>Per Day: Rs {{ product.dprice }}</h5>
          <h5>Per Week: Rs {{ product.wprice }}</h5>
          <h5>Per Month: Rs {{ product.mprice }}</h5>

        </div>

      </div>
        <hr style="border-top: 1px solid grey; width: 100%">
    {% endfor %}

  </div>




{% endblock %}

Rentalgo/products/templates/products/order.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% if error %}
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Sorry!</strong> {{ error }}
  </div>
{% endif %}
<div class="jumbotron">
    <div class="row pb-4 pt-3">
      <div class="col-2" >
        <img src="{{ product.img1.url }}" class="img-fluid ">
      </div>
      <div class="col-7">
        <h4>{{ product.prod_name }}</h4>
      </div>
      <div class="col-3">
        <!-- <a href="{% url 'detail' product.id %}"><button class="btn btn-primary btn-lg btn-block" name="button">Rent</button></a>
        <br> -->
        <h5>Per Day: Rs {{ product.dprice }}</h5>
        <h5>Per Week: Rs {{ product.wprice }}</h5>
        <h5>Per Month: Rs {{ product.mprice }}</h5>
      </div>
    </div>
    <div class="container col-4">
      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form order_form %}
        <script>
          $(function() {
            $('#id_date_range').daterangepicker({
              minDate: moment().add(1, 'days'),
              startDate: moment().add(1, 'days'),
              endDate: moment().add(1, 'days'),
              locale: {
                format: 'DD/MM/YYYY'
              }
            });
          });
        </script>
        <h5>This product is only available in: {{ product.city_choice }}</h5>
        <input type="submit" class="btn btn-primary" value="Pay Now">
      </form>
    </div>
</div>

{% endblock %}

Rentalgo/products/templates/products/paymentstatus.html
{% extends 'base.html' %}
<!-- {% block title%} My Awesome Cart Tracker{% endblock %} -->
{% block content %}
  <div class="jumbotron" style="margin-top: 12%;height: 500px">
      <h2 style="text-align: center;font-size: 5em">Order Id {{response.ORDERID}}</h2>
      {% if response.RESPCODE == '01' %}
          <br>
          <h4 style="text-align: center;font-size: 2em">  ORDER PLACED SUCCESSFULLY</h4>
      {% else %}
          <br>
          <h4 style="text-align: center;font-size: 2em">ORDER CAN NOT BE PLACED</h4>
      {% endif %}
  </div>
{% endblock %}

Rentalgo/products/templates/products/paytm.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Paytm merchant payment page</title>
  </head>
  <body>
    <h1>Redirecting you to the merchant....</h1>
    <h1>Please do not refresh your page....</h1>
    <form action="https://securegw-stage.paytm.in/order/process" method="POST" name="paytm">
      {% for key, value in param_dict.items %}
      <input type="hidden" name="{{key}}" value="{{value}}">
      {% endfor %}

    </form>
  </body>
  <script>
    document.paytm.submit()
  </script>
</html>